SELECT USER
FROM DUAL;


--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR2(30)
, PW    VARCHAR2(20)    NOT NULL
, NAME  VARCHAR2(50)    NOT NULL
, TEL   VARCHAR2(50)    NOT NULL
, EMAIL VARCHAR2(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.

SELECT *
FROM TBL_MEMBERLIST;

--○데이터 입력 쿼리문 구성
INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL)
VALUES('hello', 'java006', '이새롬', '010-8833-0594', 'lsr@email.com');
--> 한 줄 구성
INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL) VALUES('hello', 'java006', '이새롬', '010-8833-0594', 'lsr@email.com')
;

--○ 테이블 전체 조회 쿼리문 구성
SELECT ID, PW, NAME, TEL, EMAIL
FROM TBL_MEMBERLIST;
--> 한 줄 구성
SELECT ID, PW, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;

--○ 인원 수 확인 쿼리문 구성
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;
--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERLIST
;



